name: reveal-pdf
on: 
  workflow_dispatch:
    inputs:
      preso:
        description: 'Preso folder name'     
        required: true
        default: 'presentation-name'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Create "/slides" directory
        run: mkdir slides && sudo chmod 777 slides

      - name: Build PDF
        run: docker run --rm -t -v `pwd`:/presentations -v ~:/home/user astefanutti/decktape ${{ github.event.inputs.preso }}/index.html slides/${{ github.event.inputs.preso }}.pdf

      - name: Commit files
        run: |
          git config --local user.name "Slide PDFer"
          git commit -m "Add PDF render of ${{ github.event.inputs.preso }}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pdfs
